### ISSUE TITLE
Outdated instructions for /setflag command

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wiseoldman-discord-bot#249]
The "change flag" section of the bot's /help command is outdated, we should fix that:

1 - It mentions `!setflag`, we don't support prefix commands anymore, it's just `/setflag` now
2 - It shows an example of using a flag emoji as an inpout, we don't support that anymore, we only accept country codes or names now

**Comment by rorro** [comment]
I don't think it is. You might have looked at an old, previously pinned message on Discord.
https://github.com/wise-old-man/wiseoldman-discord-bot/blob/281ad35dad988683f57573ca43fd9d18048d2007/src/commands/custom.ts#L38
