### ISSUE TITLE
Name Change Review - Hours Difference?

### ISSUE THREAD

**Issue by Aluminoti** [wise-old-man/wiseoldman-discord-bot#250]
When reviewing a name change, I noticed that an archived player was showing up as maxed even though they were not. I believe this leads to the review command showing large hour differences when there really aren't any. The following screenshot should illustrate why it seems a bit weird.

I'm not exactly sure on where to put this specific issue so I'll be posting an issue on the main project as well. The issue created was https://github.com/wise-old-man/wise-old-man/issues/1516

![image](https://github.com/wise-old-man/wiseoldman-discord-bot/assets/77535556/8e41183a-9a82-4a27-be75-4615a0c3395f)

**Comment by rorro** [comment]
Should be fixed in https://github.com/wise-old-man/wise-old-man/pull/1558
